### ISSUE TITLE
Error when training driveless car game with different Training/Validation files

### ISSUE THREAD

**Issue by leonardoaraujosantos** [leonardoaraujosantos/DLMatFramework#50]
## Introduction
Problem when training with different training/validation dataset

## How to reproduce
``` bash
laraujo@lindev:~/work/DLMatFramework/virtual/tensorDriver$ python train.py --input=DrivingData.h5 --batch=4000 --checkpoint_dir=save/model.ckpt --input_val=TestData.h5 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 11.92GiB
Free memory: 11.42GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
Loading pre-trained model: save/model.ckpt
Loading training data
Load validation dataset
Number training images: 18589
Number validation images: 940
Epoch: 0, Step: 0, Loss(Val): 0.00794158
Model saved in file: ./save/model.ckpt
Shuffle data

Traceback (most recent call last):
  File "train.py", line 137, in <module>
    args.checkpoint_dir, args.epochs, args.batch, args.logdir, args.savedir)
  File "train.py", line 101, in train_network
    xs, ys = data.LoadTrainBatch(batch_size, should_augment=True)
  File "/home/laraujo/work/DLMatFramework/virtual/tensorDriver/driving_data.py", line 122, in LoadTrainBatch
    image = self.__train_xs[(self.__train_batch_pointer + i) % self.__num_train_images]
IndexError: tuple index out of range
```

**Comment by leonardoaraujosantos** [comment]
Seems ok for now
